### ISSUE TITLE
Issue with pyopengl library for mesh

### ISSUE THREAD

**Issue by WisarutBholsithi** [MPI-IS/mesh#23] opened 2019-12-04 10:52 UTC
Dear developers,
I'm trying to use mesh processing libraries (Perceiving Systems Mesh Package) as a part of TF_FLAME. However, when I tried to run  the command line "make tests", it keeps showing error as 

**AttributeError: 'NoneType' object has no attribute 'glGetError'**

Something must have gone wrong with pyopengl library so it crashed when I tried to test the mesh library.  Therefore, I need to know which version of pyopengl you have used to implement mesh library so I can reinstall the appropriate pyopengl library for this matter. 

Hope you will give the answer for this issue though.

![ErrorinPyOpenGLinMPI-ISMeshLibrary](https://user-images.githubusercontent.com/58510558/70136564-d3216580-16be-11ea-932a-57c8b3bc2b1a.jpg)

**Comment by mia-minyoung** [comment] 2019-12-12 14:50
Hi, I'm not the one who develop this lib, but I met the same problem and solved it.
So, if you installed PyOpenGL version 3.1.4, I recommend downgrade it. In my case, I used "conda install -c anaconda pyopengl" so it was downgraded as 3.1.1.a.

Might be there another issue tho, OS Error. It would be solved by install python3-opengl package by apt-get (in linux env)

**Comment by Silverster98** [comment] 2020-03-02 10:51
Hi, I also have this problem, and I downgrade pyopengl to version 3.1.1a1(v3.1.1 isn't exist). So, do you have some other methods to solve it? I use python2.7.

![微信图片_20200302185024](https://user-images.githubusercontent.com/34436920/75669848-b513d300-5cb6-11ea-9e01-e7cceda748af.png)

**Comment by Silverster98** [comment] 2020-03-03 12:57
Today, I have attempted to install pyopengl on my virtual machine. And, mesh works well. Previously, I installed it on a remote server and it failed. I think it is related to your paltform, not only software, but also hardware.

**Comment by Water-Silver** [comment] 2020-04-02 11:19
after downgrading PyOpenGL to version 3.1.0 
I had this error ('Unable to load OpenGL library', 'GL: cannot open shared object file: No such file or directory', 'GL', None)

and then doing
apt-get install python3-opengl
worked for me

**Comment by ioreshnikov** [comment] 2020-04-06 13:31
@WisarutBholsithi Thank you for reporting the issue. I have tried running `make all` and then `make tests` in a completely clean python3 virtual environment and it worked flawlessly. It looks like this issues strongly depends on the environment you are working in. Could you please report the operating system and the python version you're using to run the code?

@mia-minyoung @Silverster98 and @Water-Silver, your input, of course, would be incredibly helpful as well.

**Comment by ioreshnikov** [comment] 2020-05-28 09:31
Closing until somebody provides us with the information on how to reproduce.

**Closed by ioreshnikov** 2020-05-28 09:31 UTC
Labels: question

**Comment by presencee5** [comment] 2021-02-01 13:35
I met the same problem when running [this](https://github.com/kzhou23/shape_pose_disent) project.
I set `_error_checker` in `pythonX.X/dist-packages/OpenGL/raw/GL/_errors.py` to be `None` without calling the function `_ErrorChecker( _p, _p.GL.glGetError)` and it worked.
Althrough it's not a perfect solution, hope it can helps :-)

**Comment by Atharva-Peshkar** [comment] 2023-08-12 03:03
I was getting the same error. I'm running the code on `nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04` docker container. 

`pip install PyOpenGL==3.1.1a1` did the trick for me!
